services:
  mysql:
    image: mysql:latest
    container_name: trybe-db
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "${MYSQL_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - ${MYSQL_VOLUME_PATH}:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: "trybe-redis"
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    ports:
      - "${REDIS_PORT}:${REDIS_DOCKER_PORT}"
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: trybe-zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:${ZOOKEEPER_DOCKER_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    container_name: trybe-kafka
    ports:
      - "${KAFKA_PORT}:${KAFKA_DOCKER_PORT}"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_CLIENT_PORT}
      KAFKA_LISTENERS: EXTERNAL://0.0.0.0:${KAFKA_PORT}
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://${KAFKA_ADVERTISED_HOST}:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  jenkins:
    container_name: trybe-jenkins
    image: jenkins/jenkins
    volumes:
      - ${JENKINS_VOLUME_PATH}:/var/jenkins_home
    ports:
      - "${JENKINS_PORT}:${JENKINS_DOCKER_PORT}"

  prometheus:
    image: prom/prometheus:latest
    container_name: trybe-prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_DOCKER_PORT}"
    volumes:
      - ${PROMETHEUS_CONFIG_PATH}:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: trybe-grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_DOCKER_PORT}"
    restart: always
    depends_on:
      - prometheus

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    container_name: trybe-mysql-exporter
    ports:
      - "${MYSQL_EXPORTER_PORT}:${MYSQL_EXPORTER_DOCKER_PORT}"
    command:
      - "--mysqld.username=${MYSQL_EXPORTER_USER}"
      - "--mysqld.address=trybe-db:${MYSQL_DOCKER_PORT}"
    restart: always
    depends_on:
      - mysql

  loki:
    image: grafana/loki:latest
    container_name: trybe-loki
    ports:
      - "${LOKI_PORT}:${LOKI_DOCKER_PORT}"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ${LOKI_VOLUME_PATH}:/loki

